// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfbhH9reruRqW898GaFL7bA-9M6tncwuk',
    appId: '1:530495360476:web:1da304b8c8ab0153279319',
    messagingSenderId: '530495360476',
    projectId: 'cryptext-7c891',
    authDomain: 'cryptext-7c891.firebaseapp.com',
    storageBucket: 'cryptext-7c891.appspot.com',
    measurementId: 'G-HR6YQY2CV3',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-CQuMwUXiWR18J50i5r83r99mIIOEKQ',
    appId: '1:530495360476:android:47ae426952ce01cd279319',
    messagingSenderId: '530495360476',
    projectId: 'cryptext-7c891',
    storageBucket: 'cryptext-7c891.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAukiHZjyM_RDOWP9uBUpYVmWuevvkyXLI',
    appId: '1:530495360476:ios:e10219f616b4ecf9279319',
    messagingSenderId: '530495360476',
    projectId: 'cryptext-7c891',
    storageBucket: 'cryptext-7c891.appspot.com',
    iosBundleId: 'com.nodamngoodstudios.cryptext',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAukiHZjyM_RDOWP9uBUpYVmWuevvkyXLI',
    appId: '1:530495360476:ios:e10219f616b4ecf9279319',
    messagingSenderId: '530495360476',
    projectId: 'cryptext-7c891',
    storageBucket: 'cryptext-7c891.appspot.com',
    iosBundleId: 'com.nodamngoodstudios.cryptext',
  );
}
